name: ai_personal_assistant
description: "An AI-powered personal assistant with voice recognition and smart automation"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2

  # Speech Recognition & Text-to-Speech
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5

  # UI & Animations
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  flutter_animate: ^4.2.0
  animated_text_kit: ^4.2.2
  confetti: ^0.7.0

  # Storage & Database
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  intl: ^0.18.1
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.2

  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # Notifications
  flutter_local_notifications: ^16.3.0

  # Audio & Media
  audioplayers: ^5.2.1
  record: ^5.0.4

  # Charts & Data Visualization
  fl_chart: ^0.65.0

  # Calendar & Time
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/images/
    - assets/sounds/
    - assets/icons/ 